language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - python setup.py install -v
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=hashdb2
after_success:
  - coveralls
