language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - python setup.py install -v
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=hashdb2
after_success:
  - coveralls
addons:
  apt:
    packages:
      - sqlite3
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3
